### ISSUE TITLE
Influxdb not starting, timeout

### ISSUE THREAD

**Issue by alteredtech** [bitnami/bitnami-docker-influxdb#10]
**Description**

I am having trouble with influxdb not timing out. It will stay on "Starting InfluxDB in background" then will timeout waiting for the port state.

**Steps to reproduce the issue:**

Pull image 2.1.1
Perform docker run --env INFLUXDB_HTTP_AUTH_ENABLED=false --env INFLUXDB_ADMIN_USER_PASSWORD='Adm!nPassword' --env INFLUXDB_ADMIN_USER_TOKEN='token-token-token-token' --rm --volume ~/Backups/influxdb/data:/bitnami/influxdb -p "8086:8086"   bitnami/influxdb:2.1.1
watch docker logs influxdb

**Describe the results you received:**

This is the log I get when attempt to run the container.

```
influxdb 00:04:29.93 INFO  ==> Starting InfluxDB in background...
timeout reached before the port went into state "inuse"
influxdb 00:04:59.93 INFO  ==> Stopping InfluxDB...
```

**Describe the results you expected:**

This is what I expect to get when starting the container.

```
influxdb 23:45:42.55 INFO  ==> Starting InfluxDB in background...
influxdb 23:45:45.07 INFO  ==> Deploying InfluxDB from scratch
influxdb 23:45:45.08 INFO  ==> Creating primary setup...
User	Organization	Bucket
admin	primary		primary
influxdb 23:45:45.64 INFO  ==> Stopping InfluxDB...

influxdb 23:45:45.64 INFO  ==> ** InfluxDB setup finished! **
Terminated
influxdb 23:45:45.66 INFO  ==> ** Starting InfluxDB **
```

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

Docker version 20.10.12 and tried 20.10.7
OS: 20.04.3 LTS (Focal Fossa)
container version: 2.1.1
docker info output
```
packer@database-1:~$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-96-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.155GiB
 Name: database-1
 ID: Y6LP:KFRZ:X42S:BM7Z:LHT4:5OIK:ZKSI:H67C:WWEE:P4GC:GSID:EKD7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

I have found similar issue but were related to [mongodb](https://stackoverflow.com/questions/67112205/bitnami-mongodb-shard-timeout-reached-before-the-port-went-into-state-inuse) or charts.
[This recent post.](https://github.com/bitnami/charts/issues/5519)
[One led me here](https://github.com/bitnami/bitnami-docker-influxdb/blob/a8fa76b85080e82d3bdf941a106d67edde2a4c1f/2/debian-10/rootfs/opt/bitnami/scripts/libinfluxdb.sh#L400) 

I can take the docker run command onto my arch desktop system and it runs without issue. My main method of deploying the container is with ansible but even stripping it to a normal docker run it does not work. I have postgres working on the same host.
As I was writing this issue, I tried using tag 1 and that works as it should.

**Comment by javsalgar** [comment]
Hi,

Does the issue occur when not bind-mounting volumes? This could be due to a permission issue.

**Comment by alteredtech** [comment]
Few things.
Tried the no volumes and that worked.
Had it create the folder itself so influx-data2 was not present. This is the permissions set on the folder.
drwxr-xr-x  2 root   root   4096 Feb  1 15:41 influx-data2

I looked through closed issues and [found this](https://github.com/bitnami/bitnami-docker-influxdb/issues/3). This worked to let it start. It seems it does not create correct permissions for the folder out of the box.

Now I just need to see if I can get it working with an nfs mount, since it seems like it is the same issue.

**Comment by alteredtech** [comment]
Figured out permission issues on NAS

**Comment by alteredtech** [comment]
Something I have also noticed is that when I test a recreation with the persistent data volume on a host bind mount. The container throws an error that it cant open the boltdb. To the documentation, all you need to do is set the path to your host and on /bitnami/influxdb then you have persistent data through container recreation. I have not found that be the case. In order to get this working, you have to set the folder to be chmod 777, then no errors are thrown.

**Comment by javsalgar** [comment]
Bind mounting volumes are always problematic. This is a configuration we don't actively test or support for production workloads. In this sense, we recommend to use the cloud-provided volume technologies.
