### ISSUE TITLE
Provide version 1.8.10

### ISSUE THREAD

**Issue by bkmeneguello** [bitnami/bitnami-docker-influxdb#12]
### Name and Version

bitnami/influxdb:1.8.10

### What is the problem this feature will solve?

Since 1.8.10 is the last release from 1.x it's important for some deployments.

### What is the feature you are proposing to solve the problem?

Having the latest version available

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but we are only making releases of the stable version. Right now it is 2.2.x.

**Comment by rafariossaa** [comment]
I am closing this issue.
