### ISSUE TITLE
Influx will not start, permissions errors, no persistent data

### ISSUE THREAD

**Issue by konika3** [bitnami/bitnami-docker-influxdb#3]
**Description**

I have been struggling to get influxdb running on my Ubuntu 20.04 machine running docker and docker-compose. I would like to have persistent data to my `/home/konika/docker/influxdb` folder. Unable to have any results with the influxdb/influxdb:latest docker image, I tried bitnami's influxdb image.

Using either of the options in the readme (using `docker run` or docker-compose) I get a slew of different errors at startup.

Thank you!!!

**Steps to reproduce the issue:**

**docker-compose:**

```
  influxdb:
    container_name: influxdb
    image: docker.io/bitnami/influxdb:latest
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - /home/konkia/docker/influxdb:/bitnami/influxdb
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=mypassword123
```

The directory `/home/konika/docker/influxdb` was automatically created when running docker-compose. The directory was created with root as the owner, and permissions: `drwxr-xr-x+ 2 root  root  4096 Dec 12 15:08 influxdb`

Output of influxdb logs:

```
Attaching to influxdb
influxdb      | influxdb 20:08:37.69
influxdb      | influxdb 20:08:37.69 Welcome to the Bitnami influxdb container
influxdb      | influxdb 20:08:37.70 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-influxdb
influxdb      | influxdb 20:08:37.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-influxdb/issues
influxdb      | influxdb 20:08:37.71
influxdb      | influxdb 20:08:37.72 INFO  ==> ** Starting InfluxDB setup **
influxdb      | influxdb 20:08:37.79 INFO  ==> Initializing InfluxDB...
influxdb      | influxdb 20:08:37.80 INFO  ==> No injected configuration files found. Creating default config files...
influxdb      | influxdb 20:08:37.81 INFO  ==> Deploying InfluxDB from scratch
influxdb      | influxdb 20:08:37.82 INFO  ==> Starting InfluxDB in background...
influxdb      | timeout reached before the port went into state "inuse"
influxdb      | influxdb 20:09:07.83 INFO  ==> Stopping InfluxDB...
influxdb exited with code 1
```

I tried changing the ports to other numbers, but I received the same error as above.

**docker run:**
After purging and pruning my entire environment and deleting any folders it created, I ran the following command and received a permissions error:

```
konika@dockermachine:~/docker$ docker run \
>   --volume /home/konika/influxdb-persistence:/bitnami/influxdb \
>   --env INFLUXDB_HTTP_AUTH_ENABLED=false \
>   bitnami/influxdb:latest
influxdb 20:14:21.51
influxdb 20:14:21.51 Welcome to the Bitnami influxdb container
influxdb 20:14:21.52 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-influxdb
influxdb 20:14:21.52 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-influxdb/issues
influxdb 20:14:21.52
influxdb 20:14:21.53 INFO  ==> ** Starting InfluxDB setup **
influxdb 20:14:21.57 WARN  ==> Authentication is disabled over HTTP and HTTPS. For safety reasons, enable it in a production environment.
influxdb 20:14:21.58 WARN  ==> The INFLUXDB_ADMIN_USER environment variable will be ignored since authentication is disabled.
influxdb 20:14:21.59 INFO  ==> Initializing InfluxDB...
influxdb 20:14:21.60 INFO  ==> No injected configuration files found. Creating default config files...
influxdb 20:14:21.60 INFO  ==> Deploying InfluxDB from scratch
influxdb 20:14:21.61 INFO  ==> Stopping InfluxDB...

influxdb 20:14:21.62 INFO  ==> ** InfluxDB setup finished! **
influxdb 20:14:21.66 INFO  ==> ** Starting InfluxDB **
ts=2020-12-12T20:14:21.703880Z lvl=info msg="InfluxDB starting" log_id=0R29Hh1l000 version=1.8.3 branch=1.8 commit=563e6c3d1a7a2790763c6289501095dbec19244e
ts=2020-12-12T20:14:21.703956Z lvl=info msg="Go runtime" log_id=0R29Hh1l000 version=go1.13.8 maxprocs=8
run: create server: mkdir all: mkdir /bitnami/influxdb/meta: permission denied
```

The folder created has the following permissions: `drwxr-xr-x  2 root  root  4096 Dec 12 15:14 influxdb-persistence`

**Additional information you deem important (e.g. issue happens only occasionally):**

These two errors happen consistently. I have installed Ubuntu 20.04 on a spare laptop to test, and receive the same errors as above. Both machines have the latest `apt upgrade`. 

I have also tried creating the directories manually before running any of the aforementioned commands with identical results.

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:40 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

- Output of `uname -a`:

```
Linux dockermachine 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

First machine is an Ubuntu 20.04 VM, 16GB RAM running in ESXi v7. Second machine is a Lenovo T410i laptop also running Ubuntu 20.04, but running bare metal. Third is Debian 10.5 VM.

**Comment by andresbono** [comment]
Hi @konika3, both issues seems to be related to permissions in the volume. The container runs with the `1001` user which belongs to the root group. If you give write permissions to the group in directory you are trying to mount, the container should work fine.

In the first case you need to execute:

```
sudo chmod g+w /home/konkia/docker/influxdb
```

In the second one:

```
sudo chmod g+w /home/konika/influxdb-persistence
```

Let us know if this works.

Just for you to know, we are planning to release the new version of InfluxDB 2.0 in the following days.

**Comment by konika3** [comment]
Thanks so much @andresbono :)

I spent hours and hours searching for something that mentioned this, but never found a single hit. I probably was searching for the wrong thing. It seems though as if more people would have this issue. 

Thanks again, and best regards!
