### ISSUE TITLE
Init scripts fail when authentication is enabled

### ISSUE THREAD

**Issue by stefan-fast** [bitnami/bitnami-docker-influxdb#4]
**Description**

If the environment variable `INFLUXDB_HTTP_AUTH_ENABLED` is set to `true` and there is an init script in `.txt` format, the execution of the said init script will fail because authentication parameters are not set. 

**Steps to reproduce the issue:**

Run the container with `INFLUXDB_HTTP_AUTH_ENABLED` set to `true` and some init script `*.txt` inside `/docker-entrypoint-initdb.d`.

E.g. the first line in my init script is:

```
CREATE DATABASE prometheus;
```

**Describe the results you received:**

In debug mode, I get the following log output:
```
influxdb 14:36:11.91 DEBUG ==> Executing /docker-entrypoint-initdb.d/initdb.txt
[httpd] 127.0.0.1 - - [28/Dec/2020:14:36:11 +0000] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/1.8.3" 08217964-491a-11eb-8002-b6a448c70e21 46
[httpd] 127.0.0.1 - - [28/Dec/2020:14:36:11 +0000] "POST /query?chunked=true&db=&epoch=ns&q=CREATE+DATABASE+prometheus%3B HTTP/1.1" 401 55 "-" "InfluxDBShell/1.8.3" 082188e8-491a-11eb-8003-b6a448c70e21 120
unable to parse authentication credentials
ERR: unable to parse authentication credentials
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```
The container will fail to start and shutsdown after this error:
```
influxdb 14:36:11.93 INFO  ==> Stopping InfluxDB...
```

**Describe the results you expected:**

The authentication parameters should be passed when executing `*.txt` init scripts and `INFLUXDB_HTTP_AUTH_ENABLED` is set to `true` and the execution should work.

**Additional information you deem important (e.g. issue happens only occasionally):**

If the environment variable `INFLUXDB_HTTP_AUTH_ENABLED` is set to `false` everything works as expected.

The call to `influxdb_execute_query` at [libinfluxdb.sh#L494](https://github.com/bitnami/bitnami-docker-influxdb/blob/6fe4d684833061cf7b7cb32072b9e69845f7991b/1/debian-10/rootfs/opt/bitnami/scripts/libinfluxdb.sh#L494) is missing the second parameter to enable authentication parameters.

**Version**

- Output of `docker version`:

```
Docker version 20.10.0, build 7287ab3
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 135
  Running: 74
  Paused: 0
  Stopped: 61
 Images: 306
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.49GiB
 Name: docker-desktop
 ID: JPQD:EZ2J:LURH:LLCK:U4LW:A7TL:OKNS:BMJL:SSX2:J5JS:GJTK:GTJB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 449
  Goroutines: 347
  System Time: 2020-12-28T14:52:59.9648166Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I am using the [Bitnami InfluxDB Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/influxdb) to deploy on a Kubernetes running on Docker for MAC and am experiencing this issue.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback. Are you able to make it work with `.sh` scripts instead of `.txt` files? There you could execute commands passing the proper authentication mechanisms.

**Comment by javsalgar** [comment]
This is just to confirm there's a workaround, we should be able to make the `.txt` files work with the authentication enabled, just like with other solutions.

**Comment by stefan-fast** [comment]
Yeah, it can be worked around with `.sh` scripts pretty easily.

As long as there is an `INFLUXDB_ADMIN_USER` and `INFLUXDB_ADMIN_USER_PASSWORD` configured with the containers environment variables, so the admin user is created before calling the scripts, the following is possible:

`initdb.sh`
```
#!/bin/sh
influx -host 127.0.0.1 -port "$INFLUXDB_HTTP_PORT_NUMBER" -username "${INFLUXDB_ADMIN_USER}" -password "${INFLUXDB_ADMIN_USER_PASSWORD}" -execute "CREATE DATABASE prometheus;"
```

**Comment by javsalgar** [comment]
Thanks for letting us know, I will open the task for evaluation. As there's a current workaround, I cannot guarantee an ETA. We will update the ticket as soon as we have more news

**Comment by javsalgar** [comment]
Not stale

**Comment by jicki** [comment]
Encountered the same problem

**Comment by javsalgar** [comment]
I'm afraid it is still in our backlog. As soon as we have more news, we will update this ticket.

**Comment by fmulero** [comment]
This requests has more than a year and I'm afraid there is no plan to implement it in short term.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
