### ISSUE TITLE
Update to v2.1.1

### ISSUE THREAD

**Issue by abhi1693** [bitnami/bitnami-docker-influxdb#8]
https://github.com/influxdata/influxdb/releases/tag/v2.1.1

**Comment by miguelaeh** [comment]
Hi @abhi1693 ,
I will close this issue since it does not have a proper description. We can track it on the associated PR

**Comment by abhi1693** [comment]
@miguelaeh influx released v2.1.1 a few days ago and your pipeline has still not picked it up. This version has two new features 

Notebooks
Annotations

In my pr, I have updated the app version to 2.1.1 but there is no such image that still exists

**Comment by miguelaeh** [comment]
Hi @abhi1693 ,
It is failing in our internal pipeline because the `influx` binary have been moved to a separate repository, we are working on it

**Comment by abhi1693** [comment]
@miguelaeh Is there a way that I can contribute to this?

**Comment by miguelaeh** [comment]
Hi @abhi1693 ,
Thank you very much for the offer, but I am afraid our pipeline can be only accessed by members of our team.
